source "https://rubygems.org"

# Use the current runtime Ruby version so the test app works across
# multiple Ruby versions in CI.
ruby "#{RUBY_VERSION.split('.')[0..1].join('.')}" # Just major.minor version

gem "kirei", path: "../../"

gem "puma"

gem "amazing_print"
gem "bundler"
gem "byebug"
gem "rake"
gem "sorbet"
gem "spoom"
gem "tapioca"

gem "logger" # for Ruby 2.5+

# prompt user "IO or CPU heavy?"
# gem "puma"    # CPU heavy
# gem "falcon"  # IO heavy
