source "https://rubygems.org"

ruby "3.3.1"

gem "kirei", path: "../../"

gem "puma"

gem "amazing_print"
gem "bundler"
gem "byebug"
gem "rake"
gem "sorbet"
gem "spoom"
gem "tapioca"

# prompt user "IO or CPU heavy?"
# gem "puma"    # CPU heavy
# gem "falcon"  # IO heavy
