source "https://rubygems.org"

# Use the current runtime Ruby version so the test app works across
# multiple Ruby versions in CI.
ruby RUBY_VERSION

gem "kirei", path: "../../"

gem "puma"
gem "statsd-instrument", "~> 3.0"

gem "amazing_print"
gem "bundler"
gem "byebug"
gem "rake"
gem "sorbet"
gem "spoom"
gem "tapioca"

gem "logger" # for Ruby 2.5+
gem 'rbs', '4.0.0.dev.5' # https://github.com/Shopify/tapioca/issues/2336#issuecomment-3476622788

# prompt user "IO or CPU heavy?"
# gem "puma"    # CPU heavy
# gem "falcon"  # IO heavy
