inherit_gem:
  rubocop-dbl:
    - config/dbl.yml

AllCops:
  TargetRubyVersion: 3
  Exclude:
    - 'vendor/**/*'
    - 'sorbet/**/*'
    - 'spec/test_app/**/*'
    - 'lib/cli/**/*'
    - 'bin/kirei' # for now

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Layout/LineLength:
  Max: 120
