plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorbet

inherit_from:
  - cops/layout.yml
  - cops/lint.yml
  - cops/metrics.yml
  - cops/naming.yml
  - cops/rspec.yml
  - cops/style.yml
  - cops/types.yml

AllCops:
  TargetRubyVersion: 3
  UseCache: true
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "sorbet/**/*"
    - "spec/test_app/**/*"
    - "lib/cli/**/*"
    - "bin/kirei" # for now
    - "**/tmp/**/*"
    - "**/node_modules/**/*"
    - "bin/**/*"
