gem:
  # Add your `gem` command parameters here:
  #
  exclude:
  - amazing_print
  - byebug
  - dotenv
  - erubi
  - parallel
  - prettier_print
  - rack-test
  - rbi
  - rspec
  - rspec-core
  - rspec-expectations
  - rspec-mocks
  - rspec-support
  - rubocop
  - rubocop-ast
  - rubocop-capybara
  - rubocop-dbl
  - rubocop-factory_bot
  - rubocop-packaging
  - rubocop-performance
  - rubocop-sorbet
  - spoom
  - syntax_tree
  - tapioca
  - thor
  - yard
  - yard-sorbet
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
