gem:
  # Add your `gem` command parameters here:
  #
  exclude:
    - addressable
    - amazing_print
    - ast
    - byebug
    - dotenv
    - erb
    - erubi
    - io-console
    - json-schema
    - language_server-protocol
    - lint_roller
    - mcp
    - parallel
    - pp
    - prettier_print
    - prettyprint
    - psych
    - public_suffix
    - racc
    - rainbow
    - rbi
    - rdoc
    - regexp_parser
    - reline
    - rspec
    - rspec-core
    - rspec-expectations
    - rspec-mocks
    - rspec-support
    - rubocop
    - rubocop-ast
    - rubocop-capybara
    - rubocop-factory_bot
    - rubocop-packaging
    - rubocop-performance
    - rubocop-rspec
    - rubocop-sorbet
    - ruby-progressbar
    - spoom
    - syntax_tree
    - tapioca
    - thor
    - unicode-display_width
    - unicode-emoji
    - yard
    - yard-sorbet
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
