name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - head

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install TestApp gems
      run: bundle install --gemfile spec/test_app/Gemfile
    - name: Lint with RuboCop
      run: bundle exec rubocop --parallel --ignore-unrecognized-cops
      continue-on-error: ${{ matrix.ruby == 'head' }}
    - name: Type check with Sorbet
      run: bundle exec spoom srb tc
      continue-on-error: ${{ matrix.ruby == 'head' }}
    - name: Run tests with RSpec (excluding integration test)
      run: bundle exec rspec --tag ~integration
      continue-on-error: ${{ matrix.ruby == 'head' }}
    - name: Verify the dummy app boots & responds to health check
      run: |
        cd spec/test_app
        bundle exec puma -b tcp://127.0.0.1:9292 &
        sleep 5  # Give the server time to start
        curl -f http://127.0.0.1:9292/livez
        kill %1
