name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - head

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Lint with RuboCop
      run: bundle exec rubocop --parallel --ignore-unrecognized-cops
      continue-on-error: ${{ matrix.ruby == 'head' }}
    - name: Type check with Sorbet
      run: bundle exec spoom srb tc
      continue-on-error: ${{ matrix.ruby == 'head' }}
    - name: Run tests with RSpec
      run: bundle exec rspec
      continue-on-error: ${{ matrix.ruby == 'head' }}
